name: Backend Base (Lint & Test)

on:
    workflow_call:

jobs:
    lint:
        name: Lint Backend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: starter/backend
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Backend Environment
              # This calls the composite action we created
              uses: ./.github/actions/backend-setup

            - name: Run linting
              run: pipenv run flake8 .

    test:
        name: Test Backend
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: starter/backend
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Backend Environment
              uses: ./.github/actions/backend-setup

            - name: Run tests
              run: pipenv run pytest
